# -*- coding: utf-8 -*-
"""CompanyNewsNLP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cNWo-YPHrOjwEs0D3luqvbXQlhB1pePe

## **Obtaining News Data**
"""

import requests

url = "https://biztoc.p.rapidapi.com/news/source/bbc"

headers = {
	"x-rapidapi-key": "98d34b126dmshd9e0026c2537006p10c39ejsn1cad76109fbc",
	"x-rapidapi-host": "biztoc.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

if response.status_code == 200:
    data = response.json()
    for item in data:
        print(f"Title: {item['title']}")
        print(f"Body: {item['body']}")
        print(f"Published: {item['published']}")
        print(f"Image: {item['img']['s']}")
        print(f"URL: {item['url']}")
else:
    print("Failed to fetch data:", response.status_code)

"""## **Gathering Information and Extracting Information**"""

import pandas as pd

# Create a DataFrame from the list of dictionaries
df = pd.DataFrame(response.json())

df

len(df)

print(df.columns.tolist())

for (columnName, columnData) in df.items():
    print('Column Name : ', columnName[0])
    print('Column Contents : ', columnData.values)

df['body'].values

for (columnName, columnData) in df.items():
    print('Column Name : ', columnName[0])
    print('Column Contents : ', columnData.values)

df['title'].values

import spacy


spacy.cli.download("en_core_web_sm")
nlp = spacy.load("en_core_web_sm")


def is_company_spacy(text):
    doc = nlp(text)
    for ent in doc.ents:
        if ent.label_ == "ORG":  # Organization entity
            return True
    return False

# Test Cases
print(is_company_spacy("Microsoft Corporation"))  # True
print(is_company_spacy("Elon Musk"))             # False

for i in df['title'].values:
  print(is_company_spacy(i))

for x in range(len(df['body'].values)):
  print(is_company_spacy(df['body'].values[x]))

df = df[df.apply(lambda row: is_company_spacy(row["title"]) or is_company_spacy(row["body"]), axis=1)]
df

spacy.cli.download("en_core_web_sm")
nlp = spacy.load("en_core_web_sm")

def extract_company(text):
    doc = nlp(text)
    companies = [ent.text for ent in doc.ents if ent.label_ == "ORG"]
    return companies if companies else None

# Test Cases
text1 = "I recently applied for a job at Google and Amazon."
text2 = "John is working at Tesla Inc and loves it."
text3 = "I enjoy hiking on weekends."

print(extract_company(text1))  # ['Google', 'Amazon']
print(extract_company(text2))  # ['Tesla Inc']
print(extract_company(text3))  # None

for i in df['title'].values:
  print(extract_company(i))

for x in range(len(df['body'].values)):
  print(extract_company(df['body'].values[x]))

df["companies_mentioned"] = df["body"].apply(extract_company)
df

"""## **Preparing Text for NLP**"""

def NLP_Ready_Title(df):
  df["New_Title"] = (
        df["title"]
        .str.casefold()  # Converts to lowercase and handles Unicode better
        .str.replace(r"https?://\S+", "", regex=True)  # Remove URLs
        .str.replace(r"<a[^>]*>(.*?)</a>", r"\1", regex=True)  # Remove anchor tags but keep text
        .str.replace(r"<.*?>", " ", regex=True)  # Remove all HTML tags
        .str.replace(r"\s+", " ", regex=True)  # Replace multiple spaces with a single space
        .str.strip()  # Trim leading/trailing spaces
    )

  return df



def NLP_Ready_Body(df):
  df["New_Body"] = (
        df["body"]
        .str.casefold()  # Converts to lowercase and handles Unicode better
        .str.replace(r"https?://\S+", "", regex=True)  # Remove URLs
        .str.replace(r"<a[^>]*>(.*?)</a>", r"\1", regex=True)  # Remove anchor tags but keep text
        .str.replace(r"<.*?>", " ", regex=True)  # Remove all HTML tags
        .str.replace(r"\s+", " ", regex=True)  # Replace multiple spaces with a single space
        .str.strip()  # Trim leading/trailing spaces
    )

  return df

"""## **Applying NLP**

##### **TextBlob Method**
"""

from textblob import TextBlob


def classify_sentiment(text):
    blob = TextBlob(text)
    polarity = blob.sentiment.polarity
    if polarity > 0:
        return "Positive 😊"
    elif polarity < 0:
        return "Negative 😠"
    else:
        return "Neutral 😐"

NLP_Ready_Title(df)
NLP_Ready_Body(df)

for title in df["New_Title"]:
  print(classify_sentiment(title))

for body in df["New_Body"]:
  print(classify_sentiment(body))

for title, body, companies in zip(df['New_Title'], df["New_Body"], df["companies_mentioned"]):
  if (classify_sentiment(title) == "Neutral 😐" and classify_sentiment(body) == "Positive 😊") or (classify_sentiment(title) == "Positive 😊" and classify_sentiment(body) == "Neutral 😐"):
    print(f"These companies might be worth looking at {companies}")

"""##### **BERT (Transformers) Method**

"""

from transformers import pipeline

# Load sentiment analysis pipeline
sentiment_pipeline = pipeline("sentiment-analysis")

# Iterate through the 'New_Title' column and analyze sentiment
for title in df["New_Title"]:
    sentiment = sentiment_pipeline(title)
    label = sentiment[0]['label']  # 'LABEL_0' for Negative, 'LABEL_1' for Positive
    print(f"Title: '{title}' -> Sentiment: {label}")


print()
print()


for body in df["New_Body"]:
    sentiment = sentiment_pipeline(title)
    label = sentiment[0]['label']  # 'LABEL_0' for Negative, 'LABEL_1' for Positive
    print(f"body: '{body}' -> Sentiment: {label}")

for title, body, companies in zip(df['New_Title'], df["New_Body"], df["companies_mentioned"]):
    if (sentiment_pipeline(title)[0]["label"] == 'POSITIVE' and sentiment_pipeline(body)[0]["label"] == 'POSITIVE'):
        print(f"These companies might be worth looking at: {companies}")

"""##### **NLTK (SentiWordNet) Method**

"""

import nltk
from nltk.sentiment import SentimentIntensityAnalyzer

nltk.download('vader_lexicon')

sia = SentimentIntensityAnalyzer()

text = "The movie was quite interesting but had a slow start."
print(sia.polarity_scores(text))

for title in df["New_Title"]:
  print(sia.polarity_scores(title))

for body in df["New_Body"]:
  print(sia.polarity_scores(body))

for title, body, companies in zip(df['New_Title'], df["New_Body"], df["companies_mentioned"]):
    title_scores = sia.polarity_scores(title)  # Get sentiment scores for title
    body_scores = sia.polarity_scores(body)  # Get sentiment scores for body

    if title_scores["pos"] > title_scores["neg"] and body_scores["pos"] > body_scores["neg"]:
        print(f"These companies might be worth looking at: {companies}")